# Generated by Django 6.0.7 on 2026-09-19 11:54

import core.permissions
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TR', 'Triagem'), ('SE', 'Consulta')], default='SE', max_length=2, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('AG', 'Agendado'), ('RE', 'Concluído'), ('FP', 'Falta do paciente'), ('FA', 'Falta do aluno'), ('CA', 'Cancelado')], default='AG', max_length=2, verbose_name='Situação')),
                ('scheduled_at', models.DateTimeField(verbose_name='Data e hora')),
                ('duration_minutes', models.PositiveIntegerField(default=50, verbose_name='Duração (minutos)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Presença confirmada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['scheduled_at'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(verbose_name='Data preferida')),
                ('preferred_period', models.CharField(choices=[('MO', 'Manhã'), ('AF', 'Tarde'), ('EV', 'Noite')], max_length=2, verbose_name='Período preferido')),
                ('notes', utils.fields.EncryptedTextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('AC', 'Aceita'), ('DE', 'Recusada')], default='PE', max_length=2, verbose_name='Situação')),
                ('response', models.TextField(blank=True, verbose_name='Resposta')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitada em')),
            ],
            options={
                'verbose_name': 'Solicitação de horário',
                'verbose_name_plural': 'Solicitações de horário',
                'ordering': ['-created_at'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('room_type', models.CharField(choices=[('IF', 'Infantil'), ('AD', 'Adulta')], default='AD', max_length=2, verbose_name='Tipo de sala')),
                ('status', models.CharField(choices=[('AT', 'Ativa'), ('MA', 'Em manutenção'), ('IN', 'Inativa')], default='AT', max_length=2, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['name'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')], verbose_name='Dia da semana')),
                ('start_time', models.TimeField(verbose_name='Horário')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Reservada em')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Liberada em')),
            ],
            options={
                'verbose_name': 'Reserva de sala',
                'verbose_name_plural': 'Reservas de sala',
                'ordering': ['weekday', 'start_time'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
    ]
