# Generated by Django 6.0.7 on 2026-09-19 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_initial'),
        ('scheduling', '0001_initial'),
        ('students', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='students.student', verbose_name='Aluno que atende'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Presença confirmada por'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patient.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_appointments', to='teacher.teacher', verbose_name='Professor responsável'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_appointment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Respondida por'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_requests', to='patient.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.room', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='patient.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='scheduling.room', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='students.student', verbose_name='Aluno que atende'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PE')), fields=('patient',), name='one_pending_request_per_patient', violation_error_message='Você já tem uma solicitação de horário pendente.'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('status', 'PE')), models.Q(models.Q(('status', 'PE'), _negated=True), ('answered_at__isnull', False)), _connector='OR'), name='request_answered_only_when_not_pending'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'scheduled_at'), name='room_not_double_booked'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_by__isnull', True), ('confirmed_at__isnull', False), _connector='OR'), name='presence_confirmation_has_date'),
        ),
        migrations.AddConstraint(
            model_name='roombooking',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('room', 'weekday', 'start_time'), name='room_slot_not_double_booked'),
        ),
    ]
