# Generated by Django 6.0.7 on 2026-09-19 11:54

import core.permissions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
            bases=('core.customuser',),
        ),
        migrations.CreateModel(
            name='TeacherArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_links', to='areas.areaacting', verbose_name='Área de atuação')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_links', to='teacher.teacher', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Atuação do professor',
                'verbose_name_plural': 'Atuações do professor',
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='teacher',
            name='acting_areas',
            field=models.ManyToManyField(related_name='teachers', through='teacher.TeacherArea', to='areas.areaacting', verbose_name='Áreas de atuação'),
        ),
        migrations.AddConstraint(
            model_name='teacherarea',
            constraint=models.UniqueConstraint(fields=('teacher', 'area'), name='teacher_area_unica'),
        ),
    ]
