# Generated by Django 6.0.7 on 2026-09-19 11:54

import core.permissions
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('core', '0001_initial'),
        ('patient', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stage', models.CharField(choices=[('TR', 'Triagem'), ('AT', 'Atendimento')], default='TR', max_length=2, verbose_name='Fase do estágio')),
                ('current_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_advisees', to='teacher.teacher', verbose_name='Orientador atual')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
            bases=('core.customuser',),
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('content', models.TextField(verbose_name='Avaliação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='teacher.teacher', verbose_name='Professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Avaliação de desempenho',
                'verbose_name_plural': 'Avaliações de desempenho',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('acting_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_assignments', to='areas.areaacting', verbose_name='Área de atuação')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='patient.patient', verbose_name='Paciente')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_history', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Designação de caso',
                'verbose_name_plural': 'Designações de caso',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student', 'patient'), name='one_open_case_per_student_and_patient')],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-date'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='one_attendance_per_student_per_day')],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Advising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='O  período deve estar no formato AAAA.1 ou AAAA.2 (exemplo.:2026.1).', regex='^\\d{4}\\.[12]$')], verbose_name='Período')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisee_history', to='teacher.teacher', verbose_name='Professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advising_history', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Orientação',
                'verbose_name_plural': 'Orientações',
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student',), name='student_with_at_most_one_active_advising')],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('activity_type', models.CharField(choices=[('AT', 'Atendimento'), ('TR', 'Triagem'), ('SG', 'Supervisão em Grupo'), ('PR', 'Prontuário')], max_length=2, verbose_name='Tipo de atividade')),
                ('category', models.CharField(choices=[('PA', 'Participação'), ('EX', 'Realização')], default='EX', max_length=2, verbose_name='Natureza da hora')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Horas trabalhadas')),
                ('notes', models.TextField(blank=True, verbose_name='Observação')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activities', to='scheduling.appointment', verbose_name='Agendamento de origem')),
                ('responsible_supervisor', models.ForeignKey(limit_choices_to=models.Q(('role__in', ['PR', 'SV'])), on_delete=django.db.models.deletion.PROTECT, related_name='registered_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo registro')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Atividade de estágio',
                'verbose_name_plural': 'Atividades de estágio',
                'ordering': ['-date'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('appointment', 'category'), name='one_activity_per_appointment_category')],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
    ]
