# Generated by Django 6.0.7 on 2026-09-19 11:54

import core.permissions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaActing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área de atuação',
                'verbose_name_plural': 'Áreas de atuação',
                'ordering': ['nome'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
    ]
