# Generated by Django 6.0.7 on 2026-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SA', 'Superadmin'), ('SV', 'Coordenador'), ('PR', 'Professor'), ('AD', 'Administrativo'), ('AL', 'Aluno'), ('PA', 'Paciente')], default='AL', max_length=2, verbose_name='Cargo'),
        ),
    ]
