# Generated by Django 6.0.7 on 2026-09-19 11:54

import core.permissions
import django.core.validators
import django.db.models.deletion
import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_method', models.CharField(blank=True, choices=[('SPONTANEOUS', 'Demanda espontânea'), ('REFERRED', 'Encaminhado ou indicado')], max_length=20, verbose_name='Como chegou ao Serviço Escola de Psicologia')),
                ('referral_source', utils.fields.EncryptedTextField(blank=True, verbose_name='Encaminhado ou indicado por')),
                ('has_family_member_in_service', models.BooleanField(default=False, verbose_name='Possui familiar em atendimento no SEP')),
                ('family_member_name', utils.fields.EncryptedTextField(blank=True, verbose_name='Nome do familiar em atendimento')),
                ('family_relationship', utils.fields.EncryptedTextField(blank=True, verbose_name='Parentesco com o familiar')),
                ('is_university_student', models.BooleanField(default=False, verbose_name='É aluno da Universidade de Vassouras')),
                ('course_and_period', utils.fields.EncryptedTextField(blank=True, verbose_name='Curso e período')),
                ('has_close_relationship_with_student', models.BooleanField(default=False, verbose_name='Possui relação próxima com aluno que atua no SEP')),
                ('related_student_details', utils.fields.EncryptedTextField(blank=True, verbose_name='Aluno com quem possui relação próxima')),
                ('chief_complaint', utils.fields.EncryptedTextField(verbose_name='Queixa principal')),
                ('complaint_history', utils.fields.EncryptedTextField(blank=True, verbose_name='Evolução da queixa')),
                ('history', utils.fields.EncryptedTextField(blank=True, verbose_name='Histórico')),
                ('mental_health_treatment_history', utils.fields.EncryptedTextField(blank=True, verbose_name='Histórico de tratamento em saúde mental')),
                ('medical_treatment_history', utils.fields.EncryptedTextField(blank=True, verbose_name='Histórico de tratamento médico')),
                ('has_primary_care_connection', models.BooleanField(default=False, verbose_name='Possui vínculo com a rede de atenção básica')),
                ('primary_care_details', utils.fields.EncryptedTextField(blank=True, verbose_name='Detalhes do vínculo com a atenção básica')),
                ('uses_public_service', models.BooleanField(default=False, verbose_name='Frequenta equipamento público do município')),
                ('public_service_details', utils.fields.EncryptedTextField(blank=True, verbose_name='Equipamento público frequentado')),
                ('family_history', utils.fields.EncryptedTextField(blank=True, verbose_name='Breve histórico familiar')),
                ('social_support_network', utils.fields.EncryptedTextField(blank=True, verbose_name='Rede de suporte social')),
                ('treatment_expectations', utils.fields.EncryptedTextField(blank=True, verbose_name='Expectativa em relação ao atendimento psicológico')),
                ('additional_information', utils.fields.EncryptedTextField(blank=True, verbose_name='Outras informações relevantes')),
                ('availability', utils.fields.EncryptedTextField(blank=True, verbose_name='Dias e horários disponíveis para atendimento')),
                ('accepts_waiting_room_group', models.BooleanField(default=False, verbose_name='Aceita participar de grupo de sala de espera')),
                ('summary_and_impressions', utils.fields.EncryptedTextField(blank=True, verbose_name='Resumo e impressões')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da triagem')),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EV', 'Enviada'), ('FE', 'Fechada'), ('EN', 'Encaminhada')], default='AB', max_length=2, verbose_name='Situação')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechada em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_triage_records', to=settings.AUTH_USER_MODEL, verbose_name='Fechada por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_records', to='patient.patient', verbose_name='Paciente')),
                ('student_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_triage_records', to='students.student', verbose_name='Aluno autor')),
            ],
            options={
                'verbose_name': 'Triagem',
                'verbose_name_plural': 'Triagens',
                'ordering': ['-created_at'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TriageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Parecer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('triage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='triage.triagerecord', verbose_name='Triagem')),
            ],
            options={
                'verbose_name': 'Feedback de triagem',
                'verbose_name_plural': 'Feedbacks de triagem',
                'ordering': ['-created_at'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IarvChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_self_harm_ideation', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ideação de morte ou autolesão')),
                ('self_harm', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Automutilação')),
                ('perception_thought_changes', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Alterações da percepção ou pensamento')),
                ('intense_anxiety_fear', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ansiedade ou medo intenso')),
                ('depressed_mood_withdrawal', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Humor deprimido ou retraimento')),
                ('aggressiveness_impulsivity', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Agressividade ou impulsividade')),
                ('neglect', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Negligência')),
                ('physical_psychological_violence', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Violência física ou psicológica')),
                ('sexual_abuse', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Abuso sexual')),
                ('community_violence_exposure', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Exposição à violência comunitária')),
                ('family_income', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Renda familiar')),
                ('housing', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Moradia')),
                ('health_school_access', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Acesso à saúde e escola')),
                ('school_functioning', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Escola')),
                ('development', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Desenvolvimento')),
                ('protective_caregiver', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Responsável protetivo')),
                ('school_support', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Escola')),
                ('professional_follow_up', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Acompanhamento profissional')),
                ('triage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iarv_child', to='triage.triagerecord', verbose_name='Ficha de triagem')),
            ],
            options={
                'verbose_name': 'IARV Infantil',
                'verbose_name_plural': 'IARV Infantis',
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IarvAdult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suicidal_ideation', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ideação suicida')),
                ('self_harm', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Automutilação')),
                ('psychosis_delusions_hallucinations', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Psicose, delírios ou alucinações')),
                ('anxiety_panic', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ansiedade e pânico')),
                ('depressed_mood', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Humor deprimido')),
                ('alcohol_drug_abuse', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Uso abusivo de álcool ou drogas')),
                ('domestic_violence', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Violência doméstica')),
                ('homelessness', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Situação de rua')),
                ('income_and_work', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Renda e trabalho')),
                ('healthcare_access', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Acesso à rede de saúde')),
                ('housing_conditions', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Condições de moradia')),
                ('daily_living_activities', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Atividades de vida diária')),
                ('work_or_studies', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Trabalho ou estudos')),
                ('family_relationships', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Relações familiares')),
                ('family_support', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Família')),
                ('community_support', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Comunidade')),
                ('ongoing_treatment', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Tratamento em curso')),
                ('triage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iarv_adult', to='triage.triagerecord', verbose_name='Ficha de triagem')),
            ],
            options={
                'verbose_name': 'IARV Adulto',
                'verbose_name_plural': 'IARV Adultos',
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IarvAdolescent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suicidal_ideation', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ideação suicida')),
                ('self_harm_behavior', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Comportamento autolesivo')),
                ('perception_thought_changes', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Alterações da percepção ou pensamento')),
                ('anxiety_panic', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Ansiedade ou pânico')),
                ('depressed_mood', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Humor deprimido')),
                ('impulsivity_aggressiveness', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Impulsividade ou agressividade')),
                ('alcohol_drug_use', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Uso de álcool ou drogas')),
                ('domestic_violence', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Violência doméstica')),
                ('physical_sexual_abuse', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Abuso físico ou sexual')),
                ('bullying_school_violence', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Bullying ou violência escolar')),
                ('community_violence_exposure', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Exposição à violência comunitária')),
                ('family_income', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Renda familiar')),
                ('housing_conditions', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Condições de moradia')),
                ('health_school_network_access', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Acesso à rede de saúde e escola')),
                ('school_functioning', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Escola')),
                ('family_relationships', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Relações familiares')),
                ('social_life', models.IntegerField(choices=[(0, 'Não / Ausente'), (1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Vida social')),
                ('family_caregiver_support', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Família ou cuidador')),
                ('school_community_support', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Escola ou comunidade')),
                ('professional_follow_up', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Frágil'), (2, 'Parcial'), (3, 'Presente e estável')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Acompanhamento profissional')),
                ('triage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iarv_adolescent', to='triage.triagerecord', verbose_name='Ficha de triagem')),
            ],
            options={
                'verbose_name': 'IARV Adolescente',
                'verbose_name_plural': 'IARV Adolescentes',
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
    ]
