# Generated by Django 6.0.7 on 2026-09-25 18:11

import core.permissions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('patient', '0004_patient_marital_status_patient_naturalness_and_more'),
        ('teacher', '0001_initial'),
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado em'),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='status',
            field=models.CharField(choices=[('AB', 'Aberta'), ('EV', 'Enviada'), ('FE', 'Fechada'), ('EN', 'Encaminhada'), ('EF', 'Edição finalizada')], default='AB', max_length=2, verbose_name='Situação'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ManyToManyField(to='areas.areaacting')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Supervisor_responsavel', to='teacher.teacher', verbose_name='Supervisor responsável pelo encaminhamento')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamento_paciente', to='patient.patient', verbose_name='encaminhamento de triagem do paciente')),
                ('triage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triagem_encaminhando', to='triage.triagerecord', verbose_name='triagem encaminhando')),
            ],
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
    ]
