# Generated by Django 6.0.7 on 2026-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(max_length=100, verbose_name='Escopo')),
                ('tamanho', models.CharField(blank=True, max_length=20, verbose_name='Tamanho')),
                ('status', models.CharField(choices=[('OK', 'Concluído'), ('AG', 'Agendado'), ('ER', 'Falhou')], default='AG', max_length=2)),
                ('executado_em', models.DateTimeField(blank=True, null=True)),
                ('agendado_para', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de backup',
                'verbose_name_plural': 'Registros de backup',
                'ordering': ['-executado_em', '-agendado_para'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SA', 'Superadmin'), ('SV', 'Supervisor'), ('PR', 'Professor'), ('AD', 'Administrativo'), ('AL', 'Aluno'), ('PA', 'Paciente')], max_length=2, unique=True, verbose_name='Perfil')),
                ('escopo_acesso', models.CharField(max_length=255, verbose_name='Escopo de acesso')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escopo de permissão por perfil',
                'verbose_name_plural': 'Escopos de permissão por perfil',
            },
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Servidor')),
                ('uptime_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Uptime (%)')),
                ('cpu_percent', models.PositiveSmallIntegerField(verbose_name='CPU (%)')),
                ('memoria_percent', models.PositiveSmallIntegerField(verbose_name='Memória (%)')),
                ('health', models.CharField(choices=[('OK', 'Saudável'), ('AT', 'Atenção'), ('OF', 'Indisponível')], default='OK', max_length=2)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status de servidor',
                'verbose_name_plural': 'Status de servidores',
                'ordering': ['nome'],
            },
        ),
    ]
