# Generated by Django 6.0.7 on 2026-09-19 11:54

import core.permissions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('EM', 'Emitida')], default='PE', max_length=2, verbose_name='Situação')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('start_date', models.DateField(verbose_name='Início do período')),
                ('end_date', models.DateField(verbose_name='Fim do período')),
                ('total_minutes', models.PositiveIntegerField(verbose_name='Total em minutos')),
            ],
            options={
                'verbose_name': 'Declaração de estágio',
                'verbose_name_plural': 'Declarações de estágio',
                'ordering': ['-issued_at'],
                'abstract': False,
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttendanceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('EM', 'Emitida')], default='PE', max_length=2, verbose_name='Situação')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('kind', models.CharField(choices=[('DE', 'Declaração de comparecimento'), ('AT', 'Atestado')], default='DE', max_length=2, verbose_name='Tipo')),
                ('acting_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='areas.areaacting', verbose_name='Área de atuação')),
            ],
            options={
                'verbose_name': 'Declaração de comparecimento',
                'verbose_name_plural': 'Declarações de comparecimento',
                'ordering': ['-issued_at'],
                'abstract': False,
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
    ]
