# Generated by Django 6.0.7 on 2026-09-19 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('patient', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecertificate',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scheduling.appointment', verbose_name='Atendimento'),
        ),
        migrations.AddField(
            model_name='attendancecertificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por'),
        ),
        migrations.AddField(
            model_name='attendancecertificate',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='patient.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='attendancecertificate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='students.student', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='internshipdeclaration',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por'),
        ),
        migrations.AddField(
            model_name='internshipdeclaration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='students.student', verbose_name='Aluno'),
        ),
        migrations.AddConstraint(
            model_name='attendancecertificate',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PE'), models.Q(('issued_at__isnull', False), ('issued_by__isnull', False)), _connector='OR'), name='attendancecertificate_issued_has_date_and_author'),
        ),
        migrations.AddConstraint(
            model_name='attendancecertificate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('patient__isnull', False), ('student__isnull', True)), models.Q(('patient__isnull', True), ('student__isnull', False)), _connector='OR'), name='certificate_belongs_to_one_person'),
        ),
        migrations.AddConstraint(
            model_name='internshipdeclaration',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PE'), models.Q(('issued_at__isnull', False), ('issued_by__isnull', False)), _connector='OR'), name='internshipdeclaration_issued_has_date_and_author'),
        ),
        migrations.AddConstraint(
            model_name='internshipdeclaration',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='internship_period_is_ordered'),
        ),
    ]
