# Generated by Django 6.0.7 on 2026-09-19 11:54

import core.permissions
import django.core.validators
import django.db.models.deletion
import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('core', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('flow_status', models.CharField(blank=True, choices=[('AGUARDANDO_TRIAGEM', 'Aguardando triagem'), ('EM_TRIAGEM', 'Em triagem'), ('ENCAMINHADO', 'Encaminhado'), ('AWAITING_REVIEW', 'Aguardando parecer'), ('IN_TREATMENT', 'Em atendimento'), ('DISCHARGED', 'Alta')], default='AGUARDANDO_TRIAGEM', max_length=30, verbose_name='Status do fluxo')),
                ('social_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome social')),
                ('gender_identity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identidade de gênero')),
                ('medical_record', utils.fields.EncryptedTextField(blank=True, verbose_name='Prontuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_accompanied', models.BooleanField(blank=True, null=True, verbose_name='Está acompanhado')),
                ('guardian_first_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator("^[^\\W\\d_]+(?:[ '’-][^\\W\\d_]+)*$", 'Use somente letras.', code='invalid_letters')], verbose_name='Nome do responsável')),
                ('guardian_last_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator("^[^\\W\\d_]+(?:[ '’-][^\\W\\d_]+)*$", 'Use somente letras.', code='invalid_letters')], verbose_name='Sobrenome do responsável')),
                ('guardian_relationship', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[^\\W\\d_]+(?:[ '’-][^\\W\\d_]+)*$", 'Use somente letras.', code='invalid_letters')], verbose_name='Grau de parentesco')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('responsible_teachers', models.ManyToManyField(blank=True, related_name='referred_patients', to='teacher.teacher', verbose_name='Professores responsáveis')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
            bases=(core.permissions.BusinessRulesMixin, 'core.customuser'),
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Evolução')),
                ('session_date', models.DateField(verbose_name='Data da sessão')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('acting_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress_notes', to='areas.areaacting', verbose_name='Área de atuação')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_progress_notes', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_notes', to='patient.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Evolução',
                'verbose_name_plural': 'Evoluções',
                'ordering': ['-session_date'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
    ]
