# Generated by Django 6.0.7 on 2026-09-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor/Raça'),
        ),
    ]
