# Generated by Django 6.0.7 on 2026-09-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='patient',
            name='naturalness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ocupação atual'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religião'),
        ),
        migrations.AddField(
            model_name='patient',
            name='schooling',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Escolaridade'),
        ),
    ]
