# Generated by Django 6.0.7 on 2026-09-19 11:54

import core.permissions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(blank=True, max_length=254, verbose_name='Identificação do usuário')),
                ('action', models.CharField(choices=[('LI', 'Login'), ('LO', 'Logout'), ('LF', 'Falha de login'), ('CR', 'Criação'), ('UP', 'Alteração'), ('DE', 'Exclusão'), ('AD', 'Acesso negado'), ('RC', 'Mudança de papel'), ('PC', 'Mudança de permissão'), ('EX', 'Exportação')], max_length=2, verbose_name='Ação')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='Model alvo')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='ID alvo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Alterações')),
                ('detail', models.TextField(blank=True, verbose_name='Detalhe')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
            ],
            options={
                'verbose_name': 'Log de segurança',
                'verbose_name_plural': 'Logs de segurança',
                'ordering': ['-created_at'],
            },
            bases=(core.permissions.BusinessRulesMixin, models.Model),
        ),
    ]
